In [141]:
import pandas as pd
import numpy as np

# Lê o arquivo CSV e guarda como DataFrame (tabela)
df_analise =pd.read_csv("retail_store_sales.csv")
display(df_analise)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN

In [142]:
# Mostra o tipo de cada coluna e a quantidade de valores não nulos
display(df_analise.info())

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  str
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(1), str(7)
memory usage: 1.1+ MB

None

In [143]:
# Converte a coluna de data de texto para datetime
# errors='coerce' transforma datas inválidas em NaT (data vazia), sem dar erro
df_analise["Transaction Date"] = pd.to_datetime(df_analise["Transaction Date"], errors='coerce')

# confere se a conversão funcionou
display(df_analise.info())

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  datetime64[us]
 10  Discount Applied  8376 non-null   object
dtypes: datetime64[us](1), float64(3), object(1), str(6)
memory usage: 1.1+ MB

None

In [144]:
# Lista os valores únicos da coluna, para saber o que ela contém antes de converter
display(df_analise["Discount Applied"].unique())

# Converte de object para boolean (True/False), aceitando valores vazios
df_analise["Discount Applied"] = df_analise["Discount Applied"].astype("boolean")

# Confere o resultado
display(df_analise.info())

array([True, False, nan], dtype=object)

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  datetime64[us]
 10  Discount Applied  8376 non-null   boolean
dtypes: boolean(1), datetime64[us](1), float64(3), str(6)
memory usage: 1007.1 KB

None

In [145]:
# Converte Quantity de float para inteiro (Int64 com "I" maiúsculo aceita vazios)
df_analise["Quantity"] = df_analise["Quantity"].astype("Int64")

# Confere o resultado
display(df_analise.info())

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  Int64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  datetime64[us]
 10  Discount Applied  8376 non-null   boolean
dtypes: Int64(1), boolean(1), datetime64[us](1), float64(2), str(6)
memory usage: 1019.4 KB

None

In [146]:
# Remove as linhas em que a coluna Item está vazia
df_analise = df_analise.dropna(subset=["Item"])

# Confere o resultado
display(df_analise)

# Lista os valores únicos da coluna, para saber o que ela contém antes de converter
display(df_analise["Item"].unique())

# Conta quantas vezes cada item aparece (dropna=False inclui os vazios na contagem)
df_analise["Item"].value_counts(dropna=False)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9,247.5,Credit Card,Online,2022-05-07,<NA>
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7,87.5,Digital Wallet,Online,2022-10-02,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4,152.0,Credit Card,In-store,2023-09-03,<NA>
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10,140.0,Cash,Online,2024-08-24,<NA>
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3,51.0,Cash,Online,2022-08-06,<NA>

<StringArray>
[ 'Item_10_PAT', 'Item_17_MILK',  'Item_12_BUT',  'Item_16_BEV',
  'Item_6_FOOD',  'Item_1_FOOD',  'Item_16_FUR',  'Item_22_BUT',
   'Item_3_BUT',  'Item_2_FOOD',
 ...
   'Item_3_PAT',  'Item_13_FUR',  'Item_18_PAT', 'Item_12_MILK',
 'Item_10_MILK', 'Item_16_FOOD', 'Item_19_FOOD',  'Item_14_EHE',
   'Item_3_EHE',   'Item_9_BUT']
Length: 200, dtype: str

Item
Item_2_BEV      126
Item_25_FUR     113
Item_11_FUR     110
Item_16_MILK    109
Item_1_MILK     109
               ...
Item_13_BEV       7
Item_5_BEV        7
Item_13_FUR       7
Item_21_PAT       6
Item_3_EHE        5
Name: count, Length: 200, dtype: int64

In [147]:
# Confere o resultado
display(df_analise.info())

# Confere de novo se ainda existe algum item vazio
df_analise["Item"].value_counts(dropna=False)

<class 'pandas.DataFrame'>
Index: 11362 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    11362 non-null  str
 1   Customer ID       11362 non-null  str
 2   Category          11362 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11362 non-null  float64
 5   Quantity          11362 non-null  Int64
 6   Total Spent       11362 non-null  float64
 7   Payment Method    11362 non-null  str
 8   Location          11362 non-null  str
 9   Transaction Date  11362 non-null  datetime64[us]
 10  Discount Applied  7579 non-null   boolean
dtypes: Int64(1), boolean(1), datetime64[us](1), float64(2), str(6)
memory usage: 1009.7 KB

None

Item
Item_2_BEV      126
Item_25_FUR     113
Item_11_FUR     110
Item_16_MILK    109
Item_1_MILK     109
               ...
Item_13_BEV       7
Item_5_BEV        7
Item_13_FUR       7
Item_21_PAT       6
Item_3_EHE        5
Name: count, Length: 200, dtype: int64

In [148]:
display(df_analise)

# Conta os valores de preço, incluindo vazios, para achar preços fora do padrão.
df_analise["Price Per Unit"].value_counts(dropna=False)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9,247.5,Credit Card,Online,2022-05-07,<NA>
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7,87.5,Digital Wallet,Online,2022-10-02,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4,152.0,Credit Card,In-store,2023-09-03,<NA>
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10,140.0,Cash,Online,2024-08-24,<NA>
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3,51.0,Cash,Online,2022-08-06,<NA>

Price Per Unit
33.5    647
20.0    601
21.5    593
41.0    562
15.5    533
29.0    528
38.0    516
12.5    502
6.5     497
26.0    489
23.0    486
11.0    474
27.5    472
32.0    439
36.5    426
24.5    408
5.0     405
14.0    403
9.5     381
39.5    365
8.0     356
35.0    346
30.5    340
17.0    316
18.5    277
Name: count, dtype: int64

In [149]:

# Lista das colunas numéricas que serão analisadas juntas
colunas = ["Price Per Unit", "Quantity", "Total Spent"]
 
# Mostra o tipo de dado de cada coluna da lista
display(df_analise[colunas].dtypes)
 
# Conta quantos valores vazios existem em cada coluna da lista
display(df_analise[colunas].isna().sum())
 
# Mostra as 15 primeiras linhas que têm algum valor vazio nessas colunas
display(
    df_analise.loc[
        df_analise[colunas].isna().any(axis=1),
        colunas
    ].head(15)
)

Price Per Unit    float64
Quantity            Int64
Total Spent       float64
dtype: object

Price Per Unit    0
Quantity          0
Total Spent       0
dtype: int64

Empty DataFrame
Columns: [Price Per Unit, Quantity, Total Spent]
Index: []

In [150]:
# Conta True, False e vazios na coluna Discount Applied
display(df_analise["Discount Applied"].value_counts(dropna=False))

# Mostra o total de valores ausentes na coluna
display( 
    "Valores ausentes:",
    df_analise["Discount Applied"].isna().sum()
)

Discount Applied
True     3801
<NA>     3783
False    3778
Name: count, dtype: Int64

'Valores ausentes:'

np.int64(3783)

In [151]:
# Preenche os vazios com False (assumindo que não houve desconto)
df_analise["Discount Applied"] = (
    df_analise["Discount Applied"].fillna(False)
)

# Confere se não sobrou nenhum valor vazio e como ficou a contagem
display(df_analise["Discount Applied"].value_counts(dropna=False))

Discount Applied
False    7561
True     3801
Name: count, dtype: Int64

In [152]:
# Verificação final do DataFrame após todas as alterações
display(df_analise.info())

# Salva o DataFrame limpo em CSV (index=False evita criar uma coluna extra de índice)
df_analise.to_csv("retail_store_sales_limpo.csv", index=False)

<class 'pandas.DataFrame'>
Index: 11362 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    11362 non-null  str
 1   Customer ID       11362 non-null  str
 2   Category          11362 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11362 non-null  float64
 5   Quantity          11362 non-null  Int64
 6   Total Spent       11362 non-null  float64
 7   Payment Method    11362 non-null  str
 8   Location          11362 non-null  str
 9   Transaction Date  11362 non-null  datetime64[us]
 10  Discount Applied  11362 non-null  boolean
dtypes: Int64(1), boolean(1), datetime64[us](1), float64(2), str(6)
memory usage: 1009.7 KB

None